### ISSUE TITLE
Support running FsAutocomplete on other .NET Runtimes

### ISSUE THREAD

**Issue by baronfel** [nathanjcollins/zed-fsharp#3]
The current distribution of F# for zed doesn't support running FsAutocomplete on .NET 9 preview SDKs, or any SDK that isn't explicitly supported by FSAC. When users try zed with projects that use the 9 SDK, they get errors like this in the LSP:

<details>
<summary>LSP errors</summary>

```terminal
stderr: [18:19:34.770 ERR] [ProjectLoader] Generic error while loading project /Users/u/code/fsharp3/tests/benchmarks/CompiledCodeBenchmarks/MicroPerf/CS/MicroPerfCSharp.csproj
stderr: Microsoft.Build.Exceptions.InvalidProjectFileException: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.SDK.WorkloadAutoImportPropsLocator". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
stderr:
stderr: File name: 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
stderr: at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GlobalJsonReader.GetWorkloadVersionFromGlobalJson(String globalJsonPath)
stderr: at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
stderr: at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
stderr: at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
stderr: at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
stderr: at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
stderr: at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IReadOnlyList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""  /usr/local/share/dotnet/sdk/9.0.100-preview.6.24328.19/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props
stderr: at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
stderr: at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1](IElementLocation elementLocation, String resourceName, T1 arg0)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
stderr: at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
stderr: at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, IDirectoryCacheFactory directoryCacheFactory, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
stderr: at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
stderr: at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
stderr: at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
stderr: at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
stderr: at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, Boolean interactive)
stderr: at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, Boolean interactive)
stderr: at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
stderr: at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
stderr: at Ionide.ProjInfo.ProjectLoader.createNewProject@442(String path, ProjectCollection collection, IDictionary`2 properties) in /_//src/Ionide.ProjInfo/Library.fs:line 444
stderr: at Ionide.ProjInfo.ProjectLoader.findOrCreateMatchingProject(String path, ProjectCollection collection, IDictionary`2 globalProps) in /_//src/Ionide.ProjInfo/Library.fs:line 474
stderr: at Ionide.ProjInfo.ProjectLoader.loadProject(String path, BinaryLogGeneration binaryLogs, ProjectCollection projectCollection) in /_//src/Ionide.ProjInfo/Library.fs:line 626
```
</details>

This is because FSAC needs to load the same DLLs as the SDK that's in use for the current workspace, and if the SDK in use is newer than the latest TFM that FSAC supports then FSAC needs to be launched with env vars to let it roll-forward more eagerly.

In Ionide, we've worked around this limitation with [this logic](https://github.com/ionide/ionide-vscode-fsharp/blob/main/src/Core/LanguageService.fs#L725-L939) - the purpose of which is to

* detect the SDK in use in the current workspace
* check the TFMs supported by the version of FSAC that Ionide uses (this would be slightly different for Zed since it uses the tool form)
* compute the set of environment variables that should be provided to the fsautocomplete process to allow the .NET Runtime to roll it forward (specifically [these variables](https://github.com/ionide/ionide-vscode-fsharp/blob/main/src/Core/LanguageService.fs#L848-L854))

I believe that same process should happen here so that Zed users can use more versions of the SDK and not be tightly bound to FSAC releases to bring support.

**Comment by nathanjcollins** [comment]
@baronfel thanks for the details, this is very helpful. Tested this locally and it seems like the neovim extension I use also has this issue.

When I get some time I'll see if I can implement something similar to the above in this plugin 🙂

**Comment by laurentpayot** [comment]
LSP error for me too with .NET 9.0.100 even if fsautocomplete 0.75.0 is supposed to support .NET 9 :confused: 
```
$ dotnet tool install --global fsautocomplete
You can invoke the tool using the following command: fsautocomplete
Tool 'fsautocomplete' (version '0.75.0') was successfully installed.
```
then
```
$ fsautocomplete

[22:45:59.362 ERR] [Startup] Start - LSP mode crashed
System.AggregateException: One or more errors occurred. (Header does not end with expected \r\n character sequence: )
 ---> StreamJsonRpc.BadRpcHeaderException: Header does not end with expected \r\n character sequence: 
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadHeadersAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()
   --- End of inner exception stack trace ---
   at Ionide.LanguageServerProtocol.Server.startWithSetupCore[client](FSharpFunc`2 setupRequestHandlings, IJsonRpcMessageHandler jsonRpcHandler, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 214
   at Ionide.LanguageServerProtocol.Server.startWithSetup[client](FSharpFunc`2 setupRequestHandlings, Stream input, Stream output, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 229
   at Ionide.LanguageServerProtocol.Server.start@401-1.Invoke(FSharpFunc`2 customizeRpc)
   at FsAutoComplete.Lsp.AdaptiveFSharpLspServerModule.startCore[a,a](a toolsPath, FSharpFunc`2 workspaceLoaderFactory, ISourceTextFactory sourceTextFactory, Boolean useTransparentCompiler) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/LspServers/AdaptiveFSharpLspServer.fs:line 3157
   at FsAutoComplete.Parser.lspFactory@164-1.Invoke(Unit unitVar0) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/Parser.fs:line 165
   at FsAutoComplete.Lsp.AdaptiveFSharpLspServerModule.start(FSharpFunc`2 startCore) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/LspServers/AdaptiveFSharpLspServer.fs:line 3196
```

**Comment by laurentpayot** [comment]
UPDATE: I just updated zed-fsharp to v0.0.4 (in zed plugin tab itself) and F# seems to be supported now :man_facepalming:
I hope it will help some folks.
